name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: node -e "
          import('./js/kmath.js').then(m=>{
            const {digamma, digamma12, H, EULER_GAMMA} = m;
            const close=(a,b,e=1e-10)=>{if(Math.abs(a-b)>e)throw new Error(a+'~='+b)};
            // ψ(1) = -γ
            close(digamma(1), -EULER_GAMMA, 1e-6);
            // ψ(1/2) = -γ - 2 ln 2
            close(digamma12(0.5), -EULER_GAMMA - 2*Math.log(2), 1e-12);
            // H(10) known
            close(H(10), 2.9289682539682538, 1e-12);
          });
        "
